name: Deploy Backend EC2

on:
  push:
    branches:
      - main
    paths:
      - "API/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copiar arquivos para a EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "API/"
          target: "/home/ubuntu/inventorymanager"

      - name: Build and Run Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/inventorymanager/API

            docker build -t inventory-api .

            docker stop api-container || true
            docker rm api-container || true

            docker run -d --name api-container -p 80:8080 \
              -e "ConnectionStrings__DefaultConnection=${{ secrets.DB_CONNECTION_STRING }}" \
              -e "Jwt__Key=${{ secrets.JWT_KEY }}" \
              inventory-api
